### ISSUE TITLE
Your project is good example of learning LWM2M. Can you give webpack.config.js of this project?

### ISSUE THREAD

**Issue by simonjhy** [PeterEB/quick-demo#1]

**Comment by PeterEB** [comment]
Hi, @simonjhy ! 

This project dependencies are out of date. Now, [coap-shepherd](https://github.com/PeterEB/coap-shepherd) and [coap-node](https://github.com/PeterEB/coap-node) come to v0.2.7.

If you want to reference **webpack.config.js**. You can refer to these project: 
* **webpack v1.x**: [quick-demo-boilerplate](https://github.com/PeterEB/quick-demo-boilerplate)
* **webpack v3.x**: [freebird-demo](https://github.com/freebirdjs/freebird-demo)

**Comment by simonjhy** [comment]
Thanks Perter. 
Did you have the source js codes for index.js? I want to learn how the web and coap sever communicate with websocket. I am beginner of nodejs and coap.:)

**Comment by PeterEB** [comment]
The server side source js codes are in the "app" folder. In that folder, [server.js](https://github.com/PeterEB/quick-demo/blob/master/app/server.js) is the coap network server implement and [demoApp](https://github.com/PeterEB/quick-demo/blob/master/app/demoApp.js) is the coap client nodes implement.
