### ISSUE TITLE
Server shutdowns after another "permit join" event

### ISSUE THREAD

**Issue by timSEW** [PeterEB/quick-demo#2]
Hey Peter,

The server runs and is and available, as shown in the gif, after "permit join".
The nodes join the server and are visible.

If I "permit join" again, the server crashes with some errors.
I guess not a lot of people do that though.

**Comment by PeterEB** [comment]
Hi @timSEW 

I fixed that error in the latest version.
If you have time, you could test it to see if it behave better now.

**Comment by timSEW** [comment]
Hey @PeterEB 

The server does not crash anymore, thank you.
It seems though that after another "permit join" more of the same nodes get registered. 
It is a question of preference probably, but it should be possible to do differently in ones own implementation.
